# Generated by Django 3.1.6 on 2021-03-16 05:13

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
