# Generated by Django 3.1.6 on 2021-03-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articlena_historicalarticlena'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleNA',
        ),
        migrations.DeleteModel(
            name='HistoricalArticleNA',
        ),
    ]
