# Generated by Django 3.1.6 on 2021-03-16 06:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210316_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
