# Generated by Django 3.1.6 on 2021-02-23 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210219_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 14, 48, 39, 170326, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
