# Generated by Django 3.1.6 on 2021-02-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210223_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
