# Generated by Django 3.1.6 on 2021-02-25 08:44

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
